In [112]:
seed = 42  # for reproducibility

import pickle
import numpy as np
from matplotlib import pyplot as plt
plt.rcParams["axes.grid"] = False
%matplotlib inline

import os
import sys
from pathlib import Path
import torch
import torch.nn.functional as F
from torchvision.utils import make_grid, save_image
from sklearn.metrics import plot_confusion_matrix
torch.manual_seed(seed)
sys.path.append(str(Path().absolute().parent))
plt.style.use('seaborn')

In [113]:
exp_path = Path().absolute().parent.parent.joinpath('src/experiments/0141_CDS_ResNet50_LateralityFixThenFlipAgain_TRYAGAIN')
clog_path = 'experiments/0142_CDS_ResNet50_LateralityFixThenFlipAgain_TRYAGAINClient_Logs'
all_path = Path().absolute().parent.parent.joinpath(f'src/{clog_path}/client_logs/all')

In [114]:
pickle_file = 'log.pkl'
with open(all_path.joinpath(pickle_file), 'rb') as handle:
    CDS_metrics = pickle.load(handle)
CDS_metrics['LMLD_val_AUC']   

[{'jarv': 0.8661474131821403,
  'stge': 0.8689854662235594,
  'inbreast': 0.859375,
  'bcdr': 0.9122807017543859,
  'cmmd': 0.901326444840806}]

In [111]:
np.concatenate(CDS_metrics['LMLD_val_labels'][0]['jarv']).shape

(1680, 1)

In [96]:
CDS_metrics['LMLD_val_labels']

[{'jarv': [array([[1.],
          [1.],
          [1.],
          [0.],
          [0.],
          [0.],
          [0.],
          [1.],
          [0.],
          [1.]], dtype=float32),
   array([[1.],
          [0.],
          [0.],
          [1.],
          [1.],
          [0.],
          [1.],
          [1.],
          [1.],
          [0.]], dtype=float32),
   array([[1.],
          [1.],
          [1.],
          [0.],
          [1.],
          [0.],
          [1.],
          [1.],
          [0.],
          [1.]], dtype=float32),
   array([[0.],
          [1.],
          [0.],
          [1.],
          [0.],
          [0.],
          [0.],
          [1.],
          [1.],
          [0.]], dtype=float32),
   array([[0.],
          [0.],
          [1.],
          [1.],
          [1.],
          [1.],
          [0.],
          [1.],
          [1.],
          [0.]], dtype=float32),
   array([[0.],
          [0.],
          [0.],
          [0.],
          [1.],
          [0.],
          [

In [84]:
CDS_metrics['local_accuracy']

[]

In [53]:
CDS_metrics['LMLD_val_AUC']

[{'jarv': 0.4581334626114173,
  'stge': 0.4758278122553953,
  'inbreast': 0.3069053708439898,
  'bcdr': 0.38020833333333337,
  'cmmd': 0.5514659116554852}]

In [38]:
CDS_metrics['LMLD_val_AUC']

[{'jarv': 0.6749626912736555,
  'stge': 0.6698166026285471,
  'inbreast': 0.7272727272727273,
  'bcdr': 0.7609890109890111,
  'cmmd': 0.5893822592249973}]

In [66]:
exp_path = Path().absolute().parent.parent.joinpath('src/experiments/0116_CDS_BALANCED_DenseNet121_LateralityFixThenFlipAgain_RandomShuffleSeeds')
clog_path = 'experiments/0117_CDS_BALANCED_DenseNet121_LateralityFixThenFlipAgain_RandomShuffleSeedsClient_Logs'
all_path = Path().absolute().parent.parent.joinpath(f'src/{clog_path}/client_logs/all')

In [56]:
pickle_file = 'log.pkl'
with open(all_path.joinpath(pickle_file), 'rb') as handle:
    CDS_metrics = pickle.load(handle)
CDS_metrics['LMLD_val_AUC']

[{'jarv': 0.7969810047916734,
  'stge': 0.7412682025266923,
  'inbreast': 0.7786458333333333,
  'bcdr': 0.8774928774928774,
  'cmmd': 0.859130738851407}]

In [22]:
cmmd_accuracy = [cmmd_metrics['GMLD_true_positives'][i] / (cmmd_metrics['GMLD_true_positives'][i] + cmmd_metrics['GMLD_false_negatives'][i]) for i in range(len(cmmd_metrics['GMLD_true_positives']))]
cmmd_sensitivity = [cmmd_metrics['GMLD_true_positives'][i] / (cmmd_metrics['GMLD_true_positives'][i] + cmmd_metrics['GMLD_false_negatives'][i]) for i in range(len(cmmd_metrics['GMLD_true_positives']))]
cmmd_specificity = [cmmd_metrics['GMLD_true_negatives'][i] / (cmmd_metrics['GMLD_true_negatives'][i] + cmmd_metrics['GMLD_false_positives'][i]) for i in range(len(cmmd_metrics['GMLD_true_negatives']))]
cmmd_f1 = [2 * cmmd_metrics['GMLD_true_positives'][i] / (2 * cmmd_metrics['GMLD_true_positives'][i] + cmmd_metrics['GMLD_false_positives'][i] + cmmd_metrics['GMLD_false_negatives'][i]) for i in range(len(cmmd_metrics['GMLD_true_positives']))]
# cmmd_AUC = [sklearn.metrics.roc_auc_score(cmmd_metrics['GMLD_labels'][i].detach().numpy(), cmmd_metrics['GMLD_predictions'][i].detach().numpy()) for i in range(len(cmmd_metrics['GMLD_true_positives']))]


In [7]:
print(inbreast_metrics['LMLD_AUC'][-1], bcdr_metrics['LMLD_AUC'][-1], stge_metrics['LMLD_AUC'][-1], jarv_metrics['LMLD_AUC'][-1], cmmd_metrics['LMLD_AUC'][-1]) 

NameError: name 'inbreast_metrics' is not defined